# Generated by Django 2.1.7 on 2020-10-19 12:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesetting',
            old_name='black_quote',
            new_name='Buttongroup1',
        ),
        migrations.RenameField(
            model_name='homesetting',
            old_name='buyer',
            new_name='Buttongroup2',
        ),
        migrations.RenameField(
            model_name='homesetting',
            old_name='headline2',
            new_name='Buttongroup3',
        ),
        migrations.RenameField(
            model_name='homesetting',
            old_name='headline3',
            new_name='aimh2',
        ),
        migrations.RenameField(
            model_name='homesetting',
            old_name='aim',
            new_name='aimp',
        ),
        migrations.RenameField(
            model_name='homesetting',
            old_name='seller',
            new_name='featuredPH1',
        ),
        migrations.RenameField(
            model_name='homesetting',
            old_name='head2Qwords',
            new_name='slider1P',
        ),
        migrations.RenameField(
            model_name='homesetting',
            old_name='head3Qwords',
            new_name='slider2P',
        ),
        migrations.RemoveField(
            model_name='homesetting',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='homesetting',
            name='question',
        ),
        migrations.RemoveField(
            model_name='homesetting',
            name='whatWeDo',
        ),
        migrations.AddField(
            model_name='homesetting',
            name='aimimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='contactformimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='featuredPP',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='front',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='linkedin',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='offerbox1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='offerbox2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='offerbox3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='offerbox4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='offerbox5',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='offerbox6',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='offerbox7',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider1A',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider1H1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider1img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider2A',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider2H1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider2img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider3A',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider3H1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider3P',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='slider3img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='homesetting',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='homesetting',
            name='facebook',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='homesetting',
            name='instagram',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='homesetting',
            name='twitter',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
