# Generated by Django 2.1.7 on 2020-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201020_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesetting',
            name='contactbgpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
