# Generated by Django 2.2 on 2020-10-24 07:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homesetting_contactbgpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instaimage', models.ImageField(null=True, upload_to='')),
                ('instalink', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='homesetting',
            name='accountpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='shoppic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homesetting',
            name='whatsappweb',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500),
        ),
    ]
