# Generated by Django 2.2 on 2020-10-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_instagrampost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesetting',
            name='siteweb',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='homesetting',
            name='whatsappweb',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
