from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class HomeSetting(models.Model):
	STATUS	=	(
		('True', 'True'),
		('False', 'False'),
		)
	title			=	models.CharField(blank=True,max_length=150)
	keywords		=	models.CharField(blank=True,max_length=150)
	description		=	models.CharField(blank=True,max_length=150)
	phone			=	models.CharField(blank=True,max_length=150)
	offerbox1		=	models.CharField(blank=True,max_length=150)
	offerbox2		=	models.CharField(blank=True,max_length=150)
	offerbox3		=	models.CharField(blank=True,max_length=150)
	offerbox4		=	models.CharField(blank=True,max_length=150)
	offerbox5		=	models.CharField(blank=True,max_length=150)
	offerbox6		=	models.CharField(blank=True,max_length=150)
	offerbox7		=	models.CharField(blank=True,max_length=150)
	slider1img		=	models.ImageField(null=True, blank=True)
	slider1H1		=	models.CharField(blank=True,max_length=150)
	slider1P		=	RichTextUploadingField(blank=True,max_length=500)
	slider1A		=	models.CharField(blank=True,max_length=150)
	slider2img		=	models.ImageField(null=True, blank=True)
	slider2H1		=	models.CharField(blank=True,max_length=150)
	slider2P		=	RichTextUploadingField(blank=True,max_length=500)
	slider2A		=	models.CharField(blank=True,max_length=150)
	slider3img		=	models.ImageField(null=True, blank=True)
	slider3H1		=	models.CharField(blank=True,max_length=150)
	slider3P		=	RichTextUploadingField(blank=True,max_length=500)
	slider3A		=	models.CharField(blank=True,max_length=150)
	featuredPH1		=	models.CharField(blank=True,max_length=150)
	featuredPP		=	models.CharField(blank=True,max_length=500)
	Buttongroup1	=	models.CharField(blank=True,max_length=150)
	Buttongroup2	=	models.CharField(blank=True,max_length=150)
	Buttongroup3	=	models.CharField(blank=True,max_length=150)
	aimh2			=	models.CharField(blank=True,max_length=150)
	aimp			=	RichTextUploadingField(blank=True,max_length=1500)
	aimimg			=	models.ImageField(null=True, blank=True)
	front			=	models.ImageField(null=True, blank=True)
	popularQuote	=	RichTextUploadingField(blank=True,max_length=500)
	quoter			=	RichTextUploadingField(blank=True,max_length=150)
	whatsappweb		=	models.CharField(blank=True,max_length=2000)
	siteweb			=	models.CharField(blank=True,max_length=2000)
	shoppic			=	models.ImageField(null=True, blank=True)
	accountpic		=	models.ImageField(null=True, blank=True)
	smtpserver		=	models.CharField(blank=True,max_length=150)
	smtpemail		=	models.CharField(blank=True,max_length=150)
	smtppassword	=	models.CharField(blank=True,max_length=150)
	smtpport		=	models.CharField(blank=True,max_length=150)
	icon			=	models.ImageField(blank=True,max_length=150)
	facebook		=	models.CharField(blank=True,max_length=350)
	twitter			=	models.CharField(blank=True,max_length=350)
	linkedin		=	models.CharField(blank=True,max_length=350)
	email			=	models.CharField(blank=True,max_length=150)
	whatsapp		=	models.CharField(blank=True,max_length=350)
	instagram		=	models.CharField(blank=True,max_length=350)
	aboutus			=	RichTextUploadingField(blank=True,max_length=1500)
	address			=	RichTextUploadingField(blank=True,max_length=500)
	contactbgpic	=	models.ImageField(null=True, blank=True)
	getintouch		=	RichTextUploadingField(blank=True,max_length=500)
	refrences		=	RichTextUploadingField(blank=True,max_length=150)
	status			=	models.CharField(blank=True, max_length=150, choices=STATUS)
	Created_at		=	models.DateTimeField(auto_now_add=True)
	Updated_at		=	models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

class AboutUs(models.Model):
	STATUS	=	(
		('True', 'True'),
		('False', 'False'),
		)
	title		=	models.CharField(blank=True,max_length=150)
	pagepic		=	models.ImageField(null=True, blank=True)
	about		=	RichTextUploadingField(blank=True,max_length=4000)
	aboutpic	=	models.ImageField(null=True, blank=True)
	top1		=	models.CharField(blank=True,max_length=150)
	top2		=	models.CharField(blank=True,max_length=150)
	top3		=	models.CharField(blank=True,max_length=150)
	top1p		=	RichTextUploadingField(blank=True,max_length=1000)
	top2p		=	RichTextUploadingField(blank=True,max_length=1000)
	top3p		=	RichTextUploadingField(blank=True,max_length=1000)
	meetteam	=	models.CharField(blank=True,max_length=150)
	teampic1	=	models.ImageField(null=True, blank=True)
	name1		=	models.CharField(blank=True,max_length=350)
	role1		=	models.CharField(blank=True,max_length=350)
	facebook1	=	models.CharField(blank=True,max_length=750)
	twitter1	=	models.CharField(blank=True,max_length=750)
	mail1		=	models.CharField(blank=True,max_length=750)
	instagram1	=	models.CharField(blank=True,max_length=750)
	description1=	RichTextUploadingField(blank=True,max_length=1000)
	teampic2	=	models.ImageField(null=True, blank=True)
	name2		=	models.CharField(blank=True,max_length=350)
	role2		=	models.CharField(blank=True,max_length=350)
	facebook2	=	models.CharField(blank=True,max_length=750)
	twitter2	=	models.CharField(blank=True,max_length=750)
	mail2		=	models.CharField(blank=True,max_length=750)
	instagram2	=	models.CharField(blank=True,max_length=750)
	description2=	RichTextUploadingField(blank=True,max_length=1000)
	teampic3	=	models.ImageField(null=True, blank=True)
	name3		=	models.CharField(blank=True,max_length=350)
	role3		=	models.CharField(blank=True,max_length=350)
	facebook3	=	models.CharField(blank=True,max_length=750)
	twitter3	=	models.CharField(blank=True,max_length=750)
	mail3		=	models.CharField(blank=True,max_length=750)
	instagram3	=	models.CharField(blank=True,max_length=750)
	description3=	RichTextUploadingField(blank=True,max_length=1000)
	teampic4	=	models.ImageField(null=True, blank=True)
	name4		=	models.CharField(blank=True,max_length=350)
	role4		=	models.CharField(blank=True,max_length=350)
	facebook4	=	models.CharField(blank=True,max_length=750)
	twitter4	=	models.CharField(blank=True,max_length=750)
	mail4		=	models.CharField(blank=True,max_length=750)
	instagram4	=	models.CharField(blank=True,max_length=750)
	description4=	RichTextUploadingField(blank=True,max_length=1000)
	status		=	models.CharField(blank=True, max_length=150, choices=STATUS)
	Created_at	=	models.DateTimeField(auto_now_add=True)
	Updated_at	=	models.DateTimeField(auto_now=True)

class InstagramPost(models.Model):
	"""docstring for InstagramPost"""
	title		=	models.CharField(max_length=150)
	instaimage	=	models.ImageField(null=True)
	instalink	=	models.CharField(max_length=5000)